ID: 2026Y-05M-07D-11h54m37s_g0Ub
PID: 258300
START_DATETIME: 2026-05-07 11:54:37.265317
FILE: /home/ywatanabe/proj/scitex-stats/examples/01_basic_ttest.py
SDIR_OUT: /home/ywatanabe/proj/scitex-stats/examples/01_basic_ttest_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-stats/examples/01_basic_ttest_out/RUNNING/2026Y-05M-07D-11h54m37s_g0Ub-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-05-07 11:54:39.423834
RUN_DURATION: 00:00:02
