"""Cross-package import gate (PS-140) for scitex-stats.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.57.0

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-stats --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex_config',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev._ecosystem._skills.skills',
    'scitex_dev.cli',
    'scitex_dev.decorators',
    'scitex_dev.linter._rules._base',
    'scitex_io.bundle',
    'scitex_logging',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves(module_name):
    # Arrange — skip on the ROOT, and only on the ROOT. PS-140's own
    # prose: banning the skip outright "would convert a legitimate
    # absence into a hard failure — a gate that cannot PASS, in place
    # of one that cannot FAIL." A lean install where a peer
    # distribution is genuinely absent must SKIP here, not fail.
    #
    # Two statements ON PURPOSE. The intermediate binding is what
    # makes the root/full-path distinction visible to a reader, which
    # is the entire point of the shape; inlining it to satisfy a
    # checker would make this file harder to read.
    root = module_name.split(".")[0]
    pytest.importorskip(root)

    # Act — a real import of the FULL dotted path. Not
    # importlib.util.find_spec, which only proves a module is
    # FINDABLE while the failures this gate exists to catch (a
    # renamed symbol re-exported through a package __init__) happen
    # at EXECUTION. And not importorskip(module_name), which skips on
    # the full path and so reports the rename as an absence.
    module = importlib.import_module(module_name)

    # Assert
    assert module is not None
