#!/usr/bin/env python3
# File: scitex_stats/_utils/_export_reports.py
# ----------------------------------------
from __future__ import annotations

"""Formatted-report exporters (HTML / Markdown / plain text).

Split out from `_normalizers.py` so the file-size budget stays
honoured. Re-exported through `_normalizers.export_report` for
backward compatibility.
"""

import os
from typing import Any, Dict, List, Union

import pandas as pd

from ._normalize_core import force_dataframe


def export_report(
    results: Union[Dict[str, Any], List[Dict[str, Any]], pd.DataFrame],
    path: str,
    title: str = "Statistical Analysis Report",
    include_summary: bool = True,
    **kwargs,
) -> str:
    """Export formatted report with colored highlights.

    Format is inferred from the path extension: ``.html`` → HTML,
    ``.md`` → Markdown, anything else → plain text.
    """
    if not isinstance(results, pd.DataFrame):
        df = force_dataframe(results)
    else:
        df = results

    _, ext = os.path.splitext(path)
    format_type = ext.lstrip(".").lower()

    if format_type == "html":
        return _export_report_html(df, path, title, include_summary)
    if format_type == "md":
        return _export_report_markdown(df, path, title, include_summary)
    return _export_report_text(df, path, title, include_summary)


def _get_scitex_signature(format_type: str = "html") -> str:
    """Generate SciTeX Stats signature for branding."""
    import datetime

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if format_type == "html":
        return f"""
        <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #ddd; text-align: center; color: #666; font-size: 12px;">
            <p>Generated by <strong style="color: #4CAF50;">SciTeX Stats</strong> | {timestamp}</p>
            <p style="font-size: 10px;">Professional Statistical Analysis Framework for Scientific Computing</p>
        </div>
        """
    if format_type == "markdown":
        return (
            f"\n\n---\n\n*Generated by **SciTeX Stats** | {timestamp}*"
            "\n\n*Professional Statistical Analysis Framework for Scientific Computing*\n"
        )
    if format_type == "text":
        bar = "=" * 80
        return (
            f"\n\n{bar}\nGenerated by SciTeX Stats | {timestamp}\n"
            f"Professional Statistical Analysis Framework for Scientific Computing\n{bar}\n"
        )
    return f"Generated by SciTeX Stats | {timestamp}"


def _export_report_html(df, path, title, include_summary):
    """Generate HTML report with styling."""
    summary_html = ""
    if include_summary and "pvalue" in df.columns:
        n_total = len(df)
        n_sig_001 = (df["pvalue"] < 0.001).sum()
        n_sig_01 = ((df["pvalue"] >= 0.001) & (df["pvalue"] < 0.01)).sum()
        n_sig_05 = ((df["pvalue"] >= 0.01) & (df["pvalue"] < 0.05)).sum()
        n_ns = (df["pvalue"] >= 0.05).sum()

        summary_html = f"""
        <div class="summary">
            <h2>Summary</h2>
            <ul>
                <li>Total tests: {n_total}</li>
                <li style="color: #FF6B6B; font-weight: bold;">p &lt; 0.001 (***): {n_sig_001}</li>
                <li style="color: #FFA500; font-weight: bold;">p &lt; 0.01 (**): {n_sig_01}</li>
                <li style="color: #FFE66D; font-weight: bold;">p &lt; 0.05 (*): {n_sig_05}</li>
                <li style="color: #999;">p &gt;= 0.05 (ns): {n_ns}</li>
            </ul>
        </div>
        """

    def style_pvalue(val):
        if pd.isna(val):
            return ""
        if val < 0.001:
            return "background-color: #FF6B6B; font-weight: bold; color: white;"
        if val < 0.01:
            return "background-color: #FFA500; font-weight: bold; color: white;"
        if val < 0.05:
            return "background-color: #FFE66D; font-weight: bold;"
        return "background-color: #E8E8E8;"

    # pandas 2.2+ renamed `Styler.applymap` → `Styler.map`. Prefer
    # the new API; fall back to `applymap` for older pandas.
    if "pvalue" in df.columns:
        styler_map = getattr(df.style, "map", None) or df.style.applymap
        styled = styler_map(style_pvalue, subset=["pvalue"])
    else:
        styled = df.style

    table_html = styled.to_html()

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }}
            h1 {{ color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }}
            .summary {{ background-color: white; padding: 15px; border-radius: 5px;
                       margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            table {{ border-collapse: collapse; width: 100%; background-color: white;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            th {{ background-color: #4CAF50; color: white; padding: 12px; text-align: left; }}
            td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
            tr:hover {{ background-color: #f5f5f5; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        {summary_html}
        <h2>Results</h2>
        {table_html}
        {_get_scitex_signature("html")}
    </body>
    </html>
    """

    with open(path, "w") as f:
        f.write(html_content)
    return path


def _export_report_markdown(df, path, title, include_summary):
    """Generate Markdown report."""
    lines = [f"# {title}\n"]

    if include_summary and "pvalue" in df.columns:
        n_total = len(df)
        n_sig = (df["pvalue"] < 0.05).sum()
        n_ns = (df["pvalue"] >= 0.05).sum()
        lines.append("## Summary\n")
        lines.append(f"- Total tests: {n_total}")
        lines.append(f"- Significant (p < 0.05): {n_sig}")
        lines.append(f"- Non-significant (p >= 0.05): {n_ns}\n")

    lines.append("## Results\n")
    lines.append(df.to_markdown(index=False))
    lines.append(_get_scitex_signature("markdown"))

    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path


def _export_report_text(df, path, title, include_summary):
    """Generate plain text report."""
    lines = [title, "=" * len(title), ""]

    if include_summary and "pvalue" in df.columns:
        n_total = len(df)
        n_sig = (df["pvalue"] < 0.05).sum()
        lines.append("SUMMARY")
        lines.append(f"Total tests: {n_total}")
        lines.append(f"Significant: {n_sig}")
        lines.append("")

    lines.append("RESULTS")
    lines.append(df.to_string(index=False))
    lines.append(_get_scitex_signature("text"))

    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path


# EOF
