ID: 2026Y-05M-07D-11h54m58s_bQCN
PID: 263352
START_DATETIME: 2026-05-07 11:54:58.277068
FILE: /home/ywatanabe/proj/scitex-stats/examples/03_multiple_comparison.py
SDIR_OUT: /home/ywatanabe/proj/scitex-stats/examples/03_multiple_comparison_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-stats/examples/03_multiple_comparison_out/RUNNING/2026Y-05M-07D-11h54m58s_bQCN-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-05-07 11:55:00.401229
RUN_DURATION: 00:00:02
