"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # PA-307 §3 test-quality has a 2164-finding backlog (STX-TQ001/002/003/007
    # — missing AAA-structure comments, short test names, multi-assert tests,
    # bare smoke tests). That cleanup is tracked separately and intentionally
    # not blocking the demo+umbrella-strip work. Mask it via the audit
    # framework's `skip_rules` channel (NOT pytest.skip) — the auditor still
    # raises a UserWarning that surfaces exactly which findings were masked
    # so the backlog can't drift unnoticed.
    audit_all_for_package('scitex-stats', skip_rules=("PA-307",))
